version: '3'

services:
  web:
    restart: always
    build: web
    depends_on:
      - banco
    links:
      - banco
    environment:
      DATABASE_URL: banco
      POSTGRES_PASSWORD: "admin"
    volumes:
      - web-data:/usr/src/app/static
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - postgres-compose-network

  banco:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bd_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - banco
    networks:
      - postgres-compose-network
    volumes:
      - ./pgadmin.json:/pgadmin4/servers.json

volumes:
  banco-data:
  web-data:
  
networks: 
  postgres-compose-network: